# Generated by Django 3.1.3 on 2020-11-14 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asortyment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(default='anything', max_length=30)),
                ('bieznik', models.CharField(default='anything', max_length=30)),
                ('szerokosc', models.CharField(default='anything', max_length=10)),
                ('profil', models.CharField(default='anything', max_length=10)),
                ('srednica', models.CharField(default='anything', max_length=10)),
                ('os', models.CharField(choices=[('Strujaca', 'Sterujaca'), ('Naped', 'Naped'), ('Naczepa', 'Naczepa')], default='anything', max_length=15)),
                ('glebokosc_bieznika', models.CharField(default='anything', max_length=10)),
                ('nosnosc', models.CharField(default='anything', max_length=10)),
                ('predkosc', models.CharField(default='anything', max_length=10)),
                ('DOT', models.CharField(default='anything', max_length=10)),
                ('magazyn', models.CharField(choices=[('Magazyn A', 'Magazyn A'), ('Magazyn B', 'Magazyn B'), ('Magazyn C', 'Magazyn C')], default='anything', max_length=10)),
                ('nap_na_zimno', models.CharField(default='anything', max_length=10)),
                ('nap_na_goraco', models.CharField(default='anything', max_length=10)),
                ('cena', models.CharField(default='anything', max_length=10)),
            ],
        ),
    ]
