# Generated by Django 3.1.3 on 2020-11-14 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asortyment',
            name='profil',
            field=models.CharField(db_column='profil', default='anything', max_length=10),
        ),
        migrations.AlterField(
            model_name='asortyment',
            name='szerokosc',
            field=models.CharField(db_column='szerokosc', default='anything', max_length=10),
        ),
    ]
