# Generated by Django 3.1.3 on 2020-11-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0002_auto_20201114_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asortyment',
            name='profil',
            field=models.CharField(default='anything', max_length=10),
        ),
        migrations.AlterField(
            model_name='asortyment',
            name='szerokosc',
            field=models.CharField(default='anything', max_length=10),
        ),
    ]
